version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    groups:
      next-and-typescript:
        patterns:
          - next
          - typescript
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
